### ISSUE TITLE
Non-ascii URLs crashes reddytt

### ISSUE THREAD

**Issue by arkonten** [johanbluecreek/reddytt#3]
E.g. like this:
```
Traceback (most recent call last):
  File "./reddytt.py", line 115, in <module>
    newer_links, links = getytlinks(link)
  File "./reddytt.py", line 32, in getytlinks
    links.append(str(link.get('href')))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 56-59: ordinal not in range(128)
```

**Comment by johanbluecreek** [comment]
Fixed in PR #5 which is now merged. Closing.
