### ISSUE TITLE
Reddytt crash on `Ctrl+C` (occationally)

### ISSUE THREAD

**Issue by johanbluecreek** [johanbluecreek/reddytt#6]
Sometimes, sending `Ctrl+C` to mpv to trigger exit for reddytt (to stop playing and save the links), makes for an ungraceful exit
```
Traceback (most recent call last):  0.000 Cache: 68s+0KB
  File "./reddytt.py", line 127, in <module>
    p.communicate()
  File "/usr/lib64/python3.5/subprocess.py", line 795, in communicate
    self.wait()
  File "/usr/lib64/python3.5/subprocess.py", line 1399, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib64/python3.5/subprocess.py", line 1349, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```
Sending `Ctrl+C` to mpv when the focus is on the mpv window makes reddytt exit and save as it should, but sending `Ctrl+C` when focus is on the command-line reproduce the above error.

**Comment by johanbluecreek** [comment]
Closing this issue. The new key-mapping should make it more convenient for users to use `q` instead of `Ctrl+C` and hence avoids this. So I'm closing this.
